# Generated by Django 5.2.7 on 2025-10-26 09:39

import voters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iddocument',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('voter_card', 'Voter Card')], default='national_id', max_length=32),
        ),
        migrations.AddField(
            model_name='iddocument',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='iddocument',
            name='validation_errors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='iddocument',
            name='validation_status',
            field=models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.AddField(
            model_name='voter',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iddocument',
            name='image',
            field=models.ImageField(upload_to=voters.models.voter_upload_path),
        ),
    ]
