# Generated by Django 5.2.7 on 2025-10-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_iddocument_document_type_iddocument_extracted_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='iddocument',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'الهوية الوطنية'), ('voter_card', 'بطاقة الناخب')], default='national_id', max_length=32),
        ),
        migrations.AlterField(
            model_name='iddocument',
            name='review_status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='iddocument',
            name='validation_status',
            field=models.CharField(blank=True, choices=[('passed', 'تم التحقق'), ('failed', 'فشل التحقق')], max_length=20),
        ),
    ]
